const menu=document.querySelector('#menu'),links=document.querySelector('#links'),modal=document.querySelector('#modal');
let returnFocus;
menu?.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'×':'☰'});
function closeMenu(){links?.classList.remove('open');menu?.setAttribute('aria-expanded','false');if(menu)menu.textContent='☰'}
links?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown'))document.querySelectorAll('.nav-dropdown[open]').forEach(el=>el.removeAttribute('open'))});
function openCounselling(trigger){returnFocus=trigger||document.activeElement;modal.classList.add('open');document.body.style.overflow='hidden';modal.querySelector('input').focus()}
function closeCounselling(){modal.classList.remove('open');document.body.style.overflow='';returnFocus?.focus()}
document.querySelectorAll('.book').forEach(b=>b.addEventListener('click',()=>openCounselling(b)));
document.querySelector('#close')?.addEventListener('click',closeCounselling);
modal?.addEventListener('click',e=>{if(e.target===modal)closeCounselling()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(modal.classList.contains('open'))closeCounselling();closeMenu()}if(e.key==='Tab'&&modal.classList.contains('open')){const f=[...modal.querySelectorAll('button,input,select,textarea,a[href]')],first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
document.querySelector('#enquiry')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);const msg=`Hello Ali Consultants, I would like free counselling.\nName: ${d.get('name')}\nPhone: ${d.get('phone')}\nDestination: ${d.get('country')}\nStudy level: ${d.get('level')}\nCourse: ${d.get('course')||'Not specified'}`;window.open('https://wa.me/923214602323?text='+encodeURIComponent(msg),'_blank','noopener');closeCounselling()});
document.querySelectorAll('.journey-experience').forEach(experience=>{const tabs=[...experience.querySelectorAll('[role="tab"]')];function activate(tab){tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;experience.querySelector('#'+t.getAttribute('aria-controls')).hidden=!active})}tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>activate(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight'||e.key==='ArrowDown')next=(index+1)%tabs.length;if(e.key==='ArrowLeft'||e.key==='ArrowUp')next=(index+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();activate(tabs[next]);tabs[next].focus()}})})});
const destinationRoutes={'United Kingdom':'united-kingdom','Australia':'australia','Canada':'canada','United States':'united-states','Germany':'germany','Malaysia':'malaysia','Türkiye':'turkiye','South Korea':'south-korea'};
document.querySelector('#study-explorer')?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target),result=document.querySelector('#explorer-result'),country=data.get('country'),level=data.get('level'),subject=String(data.get('subject')).trim();result.replaceChildren();const h3=document.createElement('h3');h3.textContent=country?`Your ${country} starting point`:'Let’s find your direction together';const p=document.createElement('p');p.textContent=`You’re exploring ${level.toLowerCase()} study${subject?' in '+subject:''}${country?' in '+country:''}. The next step is to compare your qualifications, course requirements, budget and application timing with a counsellor.`;result.append(h3,p);if(country){const a=document.createElement('a');a.className='btn btn-outline';a.href='/destinations/'+destinationRoutes[country]+'/';a.textContent='Explore '+country;result.append(a)}const button=document.createElement('button');button.type='button';button.className='btn';button.textContent='Discuss My Study Plan';button.addEventListener('click',()=>{const form=document.querySelector('#enquiry'),select=form.querySelector('[name="country"]'),selectCountry=country==='United States'?'USA':country;select.value=[...select.options].some(o=>o.value===selectCountry)?selectCountry:'Not sure yet';const levels=form.querySelector('[name="level"]');levels.value=[...levels.options].some(o=>o.value===level)?level:'Other';form.querySelector('[name="course"]').value=subject;openCounselling(button)});result.append(button);result.classList.add('show')});
if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal-motion');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.section-heading,.story-copy,.planning-story,.resource-grid').forEach(el=>observer.observe(el))}
